[metadata]
name = catalyst
version = 2.0.49
author = James Chapman
author_email = jc112358@bu.edu
description = A library for implementing the Catalyst framework
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/Materials-Informatics-Laboratory/Catalyst

[options]
package_dir =
    =src
packages = find:
python_requires = >= 3.7
install_requires =
    ase
    torch>=2.0.0
    torch-geometric>=2.0.1
    networkx
    scipy
    umap-learn
    pandas
    scikit-learn
    torch-scatter
    gputils
    periodictable

[options.packages.find]
where = src
